stages:
  - build
  - test
  - deploy

variables:
  DOCKER_IMAGE: "inflight-api"
  DOCKER_REGISTRY: "docker.io"
  DOCKER_TAG: "latest"

build:
  stage: build
  image: gradle:7.6-jdk21
  script:
    - ./gradlew clean build
  artifacts:
    paths:
      - build/libs/*.jar

test:
  stage: test
  image: gradle:7.6-jdk21
  script:
    - ./gradlew test --info
  dependencies:
    - build
  artifacts:
    paths:
      - build/test-results/test/

deploy:
  stage: deploy
  image: docker:20.10
  services:
    - docker:20.10-dind
  script:
    - echo "Building Docker image..."
    - docker build -t $DOCKER_REGISTRY/$DOCKER_IMAGE:$DOCKER_TAG .
    - echo "Pushing Docker image..."
    - docker push $DOCKER_REGISTRY/$DOCKER_IMAGE:$DOCKER_TAG
  only:
    - main
